
import Link from "next/link";

export default function Footer1() {
  return (
    <div className="bg-blue text-white font-sans">
      <main className="max-w-6xl mx-auto px-4 sm:px-6 py-10">
        {/* Header */}
        <header className="flex flex-col md:flex-row justify-between items-center">
          <h1 className="text-2xl font-semibold font-sen">Finsweet</h1>
          <nav className="mt-4 md:mt-0 flex flex-wrap gap-3 md:gap-5 font-sen text-center">
            <a href="#" className="text-white hover:underline text-sm">
              Home
            </a>
            <a href="#" className="text-white hover:underline text-sm">
              Blog
            </a>
            <a href="#" className="text-white hover:underline text-sm">
              About us
            </a>
            <a href="#" className="text-white hover:underline text-sm">
              Contact us
            </a>
            <a href="#" className="text-white hover:underline text-sm">
              Privacy Policy
            </a>
          </nav>
        </header>

        {/* Subscription Section */}
        <div className="bg-[#6d6e7519] p-5 mt-10 ">
          <div className="grid gap-5 md:grid-cols-2">
            <div className="p-5 rounded-md">
              <h2 className="text-xl md:text-2xl font-sen mb-2 font-bold">
                Subscribe to our newsletter to get the latest updates and news
              </h2>
            </div>
            <div className="p-5 rounded-md">
              <div className="flex flex-col sm:flex-row gap-3">
                <input
                  type="email"
                  placeholder="Your email address"
                  className="flex-grow p-2 border border-[#6a6a7419] bg-transparent text-sm sm:text-base text-[#74757e] rounded"
                />
                <button className="px-5 py-2 bg-[#ffd050] text-black hover:bg-[#af8f38] rounded">
                  Subscribe
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="max-w-6xl mx-auto px-4 sm:px-6 pb-6 flex flex-col md:flex-row justify-between items-center gap-4 mt-10">
        {/* Contact Information */}
        <div className="text-center md:text-left flex flex-col gap-1">
          <p className="text-sm opacity-35">
            Hello@finsweet.com | 020 7993 2905
          </p>
          <p className="text-sm opacity-35">Finstreet 118 2561 Fintown</p>
        </div>

        {/* Social Links */}
        <ul className="flex justify-center md:justify-end gap-4">
          <li>
            <Link href="https://www.github.com">
              <span className="fa-brands fa-github hover:opacity-75 cursor-pointer"></span>
            </Link>
          </li>
          <li>
            <Link href="https://www.instagram.com">
              <span className="fa-brands fa-instagram hover:opacity-75 cursor-pointer"></span>
            </Link>
          </li>
          <li>
            <Link href="https://www.facebook.com">
              <span className="fa-brands fa-facebook hover:opacity-75 cursor-pointer"></span>
            </Link>
          </li>
          <li>
            <Link href="https://www.linkedin.com">
              <span className="fa-brands fa-linkedin hover:opacity-75 cursor-pointer"></span>
            </Link>
          </li>
          <li>
            <Link href="mailto:hello@finsweet.com">
              <span className="fa-regular fa-envelope hover:opacity-75 cursor-pointer"></span>
            </Link>
          </li>
        </ul>
      </footer>
    </div>
  );
}
// import Head from "next/head";
// import Link from "next/link";

// export default function Footer1() {
//   return (
//     <div className="bg-blue text-white font-sans">
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className="max-w-6xl mx-auto py-10">
//         <header className="flex justify-between items-center">
//           <h1 className="text-2xl font-semibold font-sen ">Finsweet</h1>
//           <nav className="flex gap-5 font-sen">
//             <a href="#" className="text-white hover:underline text-sm">
//               Home
//             </a>
//             <a href="#" className="text-white hover:underline text-sm">
//               Blog
//             </a>
//             <a href="#" className="text-white hover:underline text-sm">
//               About us
//             </a>
//             <a href="#" className="text-white hover:underline text-sm">
//               Contact us
//             </a>
//             <a href="#" className="text-white hover:underline text-sm">
//               Privacy Policy
//             </a>
//           </nav>
//         </header>

//         <div className="bg-[#6d6e7519] p-5 mt-10">
//           <div className="mt-10 grid gap-5 md:grid-cols-2">
//             <div className="p-5  rounded-md">
//               <h2 className="text-2xl font-sen mb-2  font-bold ">
//                 Subscribe to our newsletter to get the latest updates and news
//               </h2>
//             </div>

//             <div className="p-5 rounded-md ">
//               <div className="flex gap-3">
//                 <input
//                   type="email"
//                   placeholder="Your email address"
//                   className="flex-grow p-2 border border-[#6a6a7419]  bg-transparent text- text-[#74757e19]"
//                 />
//                 <button className="px-5 py-2 bg-[#ffd050] text-black  hover:bg-[#af8f38]">
//                   Subscribe
//                 </button>
//               </div>
//             </div>
//           </div>
//         </div>
//       </main>

//       <footer className="max-w-6xl mx-auto p-5 flex justify-between items-center  mt-10">
//         <div className="flex flex-col gap-1">
//           <p className="text-sm opacity-35">Hello@finsweet.com 020 7993 2905</p>
//           <p className="text-sm opacity-35">Finstreet 118 2561 Fintown</p>
//         </div>

//         <ul className="flex justify-end gap-3  ">
//           <li>
//             <Link href="https://www.github.com">
//               <p className="fa-brands fa-github hover:opacity-35"></p>
//             </Link>
//           </li>
//           <li>
//             <Link href="https://www.instagram.com">
//               {" "}
//               <p className="fa-brands fa-instagram  hover:opacity-35"></p>
//             </Link>
//           </li>
//           <li>
//             <Link href="https://www.facebook.com">
//               <p className="fa-brands fa-facebook  hover:opacity-35"></p>
//             </Link>
//           </li>
//           <li>
//             <Link href="https://www.linkedin.com">
//               <p className="fa-brands fa-linkedin  hover:opacity-35"></p>
//             </Link>
//           </li>
//           <li>
//             <Link href="https://www.linkedin.com">
//               <p className="fa-regular fa-envelope  hover:opacity-35"></p>
//             </Link>
//           </li>
//         </ul>
//       </footer>
//     </div>
//   );
// }
